//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPTagThat.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPTagThat.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPTagThat the MediaPortal Tag Editor.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt File.
        /// </summary>
        public static string message_CorruptFile {
            get {
                return ResourceManager.GetString("message_CorruptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string message_Error_Title {
            get {
                return ResourceManager.GetString("message_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        public static string message_ErrorReadingFile {
            get {
                return ResourceManager.GetString("message_ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reset readonly attribute.
        /// </summary>
        public static string message_ErrorResetAttr {
            get {
                return ResourceManager.GetString("message_ErrorResetAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: {0}.
        /// </summary>
        public static string message_ErrorSave {
            get {
                return ResourceManager.GetString("message_ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no longer existing!.
        /// </summary>
        public static string message_NonExistingFile {
            get {
                return ResourceManager.GetString("message_NonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many files scanned. Running out of Memory.\r\nAborting Scan..
        /// </summary>
        public static string message_OutOfMemory {
            get {
                return ResourceManager.GetString("message_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Format.
        /// </summary>
        public static string message_UnsupportedFormat {
            get {
                return ResourceManager.GetString("message_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Files.
        /// </summary>
        public static string miscFiles_Header {
            get {
                return ResourceManager.GetString("miscFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Burner.
        /// </summary>
        public static string ribbon_AddBurner {
            get {
                return ResourceManager.GetString("ribbon_AddBurner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Conversion.
        /// </summary>
        public static string ribbon_AddConvert {
            get {
                return ResourceManager.GetString("ribbon_AddConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string ribbon_AddPlaylist {
            get {
                return ResourceManager.GetString("ribbon_AddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Number.
        /// </summary>
        public static string ribbon_AutoNumber {
            get {
                return ResourceManager.GetString("ribbon_AutoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Detect.
        /// </summary>
        public static string ribbon_BPM {
            get {
                return ResourceManager.GetString("ribbon_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn.
        /// </summary>
        public static string ribbon_BurnTab {
            get {
                return ResourceManager.GetString("ribbon_BurnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion.
        /// </summary>
        public static string ribbon_CaseConversion {
            get {
                return ResourceManager.GetString("ribbon_CaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion.
        /// </summary>
        public static string ribbon_CaseConversionMenu {
            get {
                return ResourceManager.GetString("ribbon_CaseConversionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion Options.
        /// </summary>
        public static string ribbon_CaseConversionOption {
            get {
                return ResourceManager.GetString("ribbon_CaseConversionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string ribbon_ConvertTab {
            get {
                return ResourceManager.GetString("ribbon_ConvertTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ribbon_DatabaseContextualTab {
            get {
                return ResourceManager.GetString("ribbon_DatabaseContextualTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ribbon_DatabaseTab {
            get {
                return ResourceManager.GetString("ribbon_DatabaseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Tags.
        /// </summary>
        public static string ribbon_DeleteAllTags {
            get {
                return ResourceManager.GetString("ribbon_DeleteAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ID3 V1 Tags only.
        /// </summary>
        public static string ribbon_DeleteID3V1Tags {
            get {
                return ResourceManager.GetString("ribbon_DeleteID3V1Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ID3 V2 Tags only.
        /// </summary>
        public static string ribbon_DeleteID3V2Tags {
            get {
                return ResourceManager.GetString("ribbon_DeleteID3V2Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tags.
        /// </summary>
        public static string ribbon_DeleteTags {
            get {
                return ResourceManager.GetString("ribbon_DeleteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tags.
        /// </summary>
        public static string ribbon_EditTags {
            get {
                return ResourceManager.GetString("ribbon_EditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Script.
        /// </summary>
        public static string ribbon_ExecuteScript {
            get {
                return ResourceManager.GetString("ribbon_ExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ribbon_Find {
            get {
                return ResourceManager.GetString("ribbon_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix MP3.
        /// </summary>
        public static string ribbon_FixSong {
            get {
                return ResourceManager.GetString("ribbon_FixSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cover Art.
        /// </summary>
        public static string ribbon_GetCoverArt {
            get {
                return ResourceManager.GetString("ribbon_GetCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Lyrics.
        /// </summary>
        public static string ribbon_GetLyrics {
            get {
                return ResourceManager.GetString("ribbon_GetLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify File.
        /// </summary>
        public static string ribbon_IdentifyFile {
            get {
                return ResourceManager.GetString("ribbon_IdentifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Tag Edit.
        /// </summary>
        public static string ribbon_MultiTagEdit {
            get {
                return ResourceManager.GetString("ribbon_MultiTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number on Click.
        /// </summary>
        public static string ribbon_NumberOnClick {
            get {
                return ResourceManager.GetString("ribbon_NumberOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise Files.
        /// </summary>
        public static string ribbon_Organise {
            get {
                return ResourceManager.GetString("ribbon_Organise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise.
        /// </summary>
        public static string ribbon_OrganiseFiles {
            get {
                return ResourceManager.GetString("ribbon_OrganiseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ribbon_Other {
            get {
                return ResourceManager.GetString("ribbon_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverart.
        /// </summary>
        public static string ribbon_Picture {
            get {
                return ResourceManager.GetString("ribbon_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove:.
        /// </summary>
        public static string ribbon_RemoveCommentPicture {
            get {
                return ResourceManager.GetString("ribbon_RemoveCommentPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all comments.
        /// </summary>
        public static string ribbon_RemoveComments {
            get {
                return ResourceManager.GetString("ribbon_RemoveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all pictures.
        /// </summary>
        public static string ribbon_RemovePictures {
            get {
                return ResourceManager.GetString("ribbon_RemovePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string ribbon_RenameFile {
            get {
                return ResourceManager.GetString("ribbon_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string ribbon_RenameFileMenu {
            get {
                return ResourceManager.GetString("ribbon_RenameFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File Options.
        /// </summary>
        public static string ribbon_RenameFileOptions {
            get {
                return ResourceManager.GetString("ribbon_RenameFileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ribbon_Replace {
            get {
                return ResourceManager.GetString("ribbon_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Gain.
        /// </summary>
        public static string ribbon_ReplayGain {
            get {
                return ResourceManager.GetString("ribbon_ReplayGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Tags.
        /// </summary>
        public static string ribbon_RetrieveTags {
            get {
                return ResourceManager.GetString("ribbon_RetrieveTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rip.
        /// </summary>
        public static string ribbon_RipTab {
            get {
                return ResourceManager.GetString("ribbon_RipTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Folder Thumb.
        /// </summary>
        public static string ribbon_SaveFolderThumb {
            get {
                return ResourceManager.GetString("ribbon_SaveFolderThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Tag Edit.
        /// </summary>
        public static string ribbon_SingleTagEdit {
            get {
                return ResourceManager.GetString("ribbon_SingleTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag from Filename.
        /// </summary>
        public static string ribbon_TagFromFile {
            get {
                return ResourceManager.GetString("ribbon_TagFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag from Internet.
        /// </summary>
        public static string ribbon_TagFromInternet {
            get {
                return ResourceManager.GetString("ribbon_TagFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ribbon_TagTab {
            get {
                return ResourceManager.GetString("ribbon_TagTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate MP3.
        /// </summary>
        public static string ribbon_ValidateSong {
            get {
                return ResourceManager.GetString("ribbon_ValidateSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagfilter: Active.
        /// </summary>
        public static string statusBar_FilterActive {
            get {
                return ResourceManager.GetString("statusBar_FilterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagfilter: Inactive.
        /// </summary>
        public static string statusBar_FilterInactive {
            get {
                return ResourceManager.GetString("statusBar_FilterInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}.
        /// </summary>
        public static string statusBar_NumberOfFiles {
            get {
                return ResourceManager.GetString("statusBar_NumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Selected: {0}).
        /// </summary>
        public static string statusBar_NumberOfSelectedFiles {
            get {
                return ResourceManager.GetString("statusBar_NumberOfSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeview.
        /// </summary>
        public static string treeview_Header {
            get {
                return ResourceManager.GetString("treeview_Header", resourceCulture);
            }
        }
    }
}
