//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPTagThat.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPTagThat.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPTagThat - The MediaPortal Tag Editor.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save covers with a maximum pixel width of:.
        /// </summary>
        public static string coverSearch_ChangeCoverSize {
            get {
                return ResourceManager.GetString("coverSearch_ChangeCoverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create missing folder thumb (folder.jpg) on Save.
        /// </summary>
        public static string coverSearch_CreateMissingFolderThumb {
            get {
                return ResourceManager.GetString("coverSearch_CreateMissingFolderThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed existing folder thumb (folder.jpg) on cover search.
        /// </summary>
        public static string coverSearch_EmbedExistingThumb {
            get {
                return ResourceManager.GetString("coverSearch_EmbedExistingThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Finished. Select Cover Art (Double Click or Apply Button).
        /// </summary>
        public static string coverSearch_Finished {
            get {
                return ResourceManager.GetString("coverSearch_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Album Search Site.
        /// </summary>
        public static string coverSearch_NoSites_Selected {
            get {
                return ResourceManager.GetString("coverSearch_NoSites_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Cover Art only to folder thumb. Don&apos;t touch the music file.
        /// </summary>
        public static string coverSearch_OnlySaveFolderThumb {
            get {
                return ResourceManager.GetString("coverSearch_OnlySaveFolderThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing Cover(s) on automatic tagging.
        /// </summary>
        public static string coverSearch_OverwriteExistingCover {
            get {
                return ResourceManager.GetString("coverSearch_OverwriteExistingCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Album Search Site(s).
        /// </summary>
        public static string coverSearch_Sites_Watermark {
            get {
                return ResourceManager.GetString("coverSearch_Sites_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Cover Art ... {0} Sites. Remaining: {1}.
        /// </summary>
        public static string coverSearch_Status {
            get {
                return ResourceManager.GetString("coverSearch_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Cover Search.
        /// </summary>
        public static string coverSearch_Title {
            get {
                return ResourceManager.GetString("coverSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string dialog_Apply {
            get {
                return ResourceManager.GetString("dialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialog_Cancel {
            get {
                return ResourceManager.GetString("dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string dialog_Close {
            get {
                return ResourceManager.GetString("dialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string dialog_Ok {
            get {
                return ResourceManager.GetString("dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string dialog_Search {
            get {
                return ResourceManager.GetString("dialog_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Finished. Select correct  Lyrics..
        /// </summary>
        public static string lyricsSearch_Finished {
            get {
                return ResourceManager.GetString("lyricsSearch_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Lyrics Search Site.
        /// </summary>
        public static string lyricsSearch_NoSites_Selected {
            get {
                return ResourceManager.GetString("lyricsSearch_NoSites_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to search for.
        /// </summary>
        public static string lyricsSearch_NothingToSearch {
            get {
                return ResourceManager.GetString("lyricsSearch_NothingToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lyrics Search Site(s).
        /// </summary>
        public static string lyricsSearch_Sites_Watermark {
            get {
                return ResourceManager.GetString("lyricsSearch_Sites_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Lyrics ...  {0} Sites  x {1} Songs  = {2} Songs to Search. Found: {3} Not Found: {4} Remaining: {5}.
        /// </summary>
        public static string lyricsSearch_Status {
            get {
                return ResourceManager.GetString("lyricsSearch_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Search.
        /// </summary>
        public static string lyricsSearch_Title {
            get {
                return ResourceManager.GetString("lyricsSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt File.
        /// </summary>
        public static string message_CorruptFile {
            get {
                return ResourceManager.GetString("message_CorruptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string message_Error_Title {
            get {
                return ResourceManager.GetString("message_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        public static string message_ErrorReadingFile {
            get {
                return ResourceManager.GetString("message_ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reset readonly attribute.
        /// </summary>
        public static string message_ErrorResetAttr {
            get {
                return ResourceManager.GetString("message_ErrorResetAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: {0}.
        /// </summary>
        public static string message_ErrorSave {
            get {
                return ResourceManager.GetString("message_ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File no longer existing!.
        /// </summary>
        public static string message_NonExistingFile {
            get {
                return ResourceManager.GetString("message_NonExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many files scanned. Running out of Memory.\r\nAborting Scan..
        /// </summary>
        public static string message_OutOfMemory {
            get {
                return ResourceManager.GetString("message_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have not been saved. Do you want to save the changes?.
        /// </summary>
        public static string message_Save_Changes {
            get {
                return ResourceManager.GetString("message_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string message_Save_Changes_Title {
            get {
                return ResourceManager.GetString("message_Save_Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compile of the script failed.\n\nPlease look for the error in the log and correct it..
        /// </summary>
        public static string message_Script_Compile_Failed {
            get {
                return ResourceManager.GetString("message_Script_Compile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Format.
        /// </summary>
        public static string message_UnsupportedFormat {
            get {
                return ResourceManager.GetString("message_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Files.
        /// </summary>
        public static string miscFiles_Header {
            get {
                return ResourceManager.GetString("miscFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected file(s).
        /// </summary>
        public static string miscFiles_Menu_DeleteFiles {
            get {
                return ResourceManager.GetString("miscFiles_Menu_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to &quot;folder.jpg&quot;.
        /// </summary>
        public static string miscFiles_Menu_Rename {
            get {
                return ResourceManager.GetString("miscFiles_Menu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string organise_BrowseFolder {
            get {
                return ResourceManager.GetString("organise_BrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Files instead of Moving them.
        /// </summary>
        public static string organise_Copy_Files {
            get {
                return ResourceManager.GetString("organise_Copy_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy/Move Non-Music Files (Pictures, etc.).
        /// </summary>
        public static string organise_Copy_NonMusic_Files {
            get {
                return ResourceManager.GetString("organise_Copy_NonMusic_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File already exists. Will not be replaced.
        /// </summary>
        public static string organise_FileExists {
            get {
                return ResourceManager.GetString("organise_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ = Folder: to specify that parameters in front to be used as subfoldername within target folder.
        /// </summary>
        public static string organise_Folder {
            get {
                return ResourceManager.GetString("organise_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string organise_Format {
            get {
                return ResourceManager.GetString("organise_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise Files.
        /// </summary>
        public static string organise_Header {
            get {
                return ResourceManager.GetString("organise_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string organise_Options {
            get {
                return ResourceManager.GetString("organise_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Target Root Directory using Script:.
        /// </summary>
        public static string organise_Override_TargetPath {
            get {
                return ResourceManager.GetString("organise_Override_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string organise_OverWrite_Files {
            get {
                return ResourceManager.GetString("organise_OverWrite_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and Target File are the same. File skipped.
        /// </summary>
        public static string organise_SameFile {
            get {
                return ResourceManager.GetString("organise_SameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Path:.
        /// </summary>
        public static string organise_TargetPath {
            get {
                return ResourceManager.GetString("organise_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Burner.
        /// </summary>
        public static string ribbon_AddBurner {
            get {
                return ResourceManager.GetString("ribbon_AddBurner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Conversion.
        /// </summary>
        public static string ribbon_AddConvert {
            get {
                return ResourceManager.GetString("ribbon_AddConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string ribbon_AddPlaylist {
            get {
                return ResourceManager.GetString("ribbon_AddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Number.
        /// </summary>
        public static string ribbon_AutoNumber {
            get {
                return ResourceManager.GetString("ribbon_AutoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Detect.
        /// </summary>
        public static string ribbon_BPM {
            get {
                return ResourceManager.GetString("ribbon_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn.
        /// </summary>
        public static string ribbon_BurnTab {
            get {
                return ResourceManager.GetString("ribbon_BurnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion.
        /// </summary>
        public static string ribbon_CaseConversion {
            get {
                return ResourceManager.GetString("ribbon_CaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion.
        /// </summary>
        public static string ribbon_CaseConversionMenu {
            get {
                return ResourceManager.GetString("ribbon_CaseConversionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Conversion Options.
        /// </summary>
        public static string ribbon_CaseConversionOption {
            get {
                return ResourceManager.GetString("ribbon_CaseConversionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string ribbon_ConvertTab {
            get {
                return ResourceManager.GetString("ribbon_ConvertTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ribbon_DatabaseContextualTab {
            get {
                return ResourceManager.GetString("ribbon_DatabaseContextualTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ribbon_DatabaseTab {
            get {
                return ResourceManager.GetString("ribbon_DatabaseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Tags.
        /// </summary>
        public static string ribbon_DeleteAllTags {
            get {
                return ResourceManager.GetString("ribbon_DeleteAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ID3 V1 Tags only.
        /// </summary>
        public static string ribbon_DeleteID3V1Tags {
            get {
                return ResourceManager.GetString("ribbon_DeleteID3V1Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ID3 V2 Tags only.
        /// </summary>
        public static string ribbon_DeleteID3V2Tags {
            get {
                return ResourceManager.GetString("ribbon_DeleteID3V2Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layout.
        /// </summary>
        public static string ribbon_DeleteLayout {
            get {
                return ResourceManager.GetString("ribbon_DeleteLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tags.
        /// </summary>
        public static string ribbon_DeleteTags {
            get {
                return ResourceManager.GetString("ribbon_DeleteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tags.
        /// </summary>
        public static string ribbon_EditTags {
            get {
                return ResourceManager.GetString("ribbon_EditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Script.
        /// </summary>
        public static string ribbon_ExecuteScript {
            get {
                return ResourceManager.GetString("ribbon_ExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ribbon_Find {
            get {
                return ResourceManager.GetString("ribbon_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix MP3.
        /// </summary>
        public static string ribbon_FixSong {
            get {
                return ResourceManager.GetString("ribbon_FixSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cover Art.
        /// </summary>
        public static string ribbon_GetCoverArt {
            get {
                return ResourceManager.GetString("ribbon_GetCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Lyrics.
        /// </summary>
        public static string ribbon_GetLyrics {
            get {
                return ResourceManager.GetString("ribbon_GetLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify File.
        /// </summary>
        public static string ribbon_IdentifyFile {
            get {
                return ResourceManager.GetString("ribbon_IdentifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Tag Edit.
        /// </summary>
        public static string ribbon_MultiTagEdit {
            get {
                return ResourceManager.GetString("ribbon_MultiTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number on Click.
        /// </summary>
        public static string ribbon_NumberOnClick {
            get {
                return ResourceManager.GetString("ribbon_NumberOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise Files.
        /// </summary>
        public static string ribbon_Organise {
            get {
                return ResourceManager.GetString("ribbon_Organise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise.
        /// </summary>
        public static string ribbon_OrganiseFiles {
            get {
                return ResourceManager.GetString("ribbon_OrganiseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ribbon_Other {
            get {
                return ResourceManager.GetString("ribbon_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverart.
        /// </summary>
        public static string ribbon_Picture {
            get {
                return ResourceManager.GetString("ribbon_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove:.
        /// </summary>
        public static string ribbon_RemoveCommentPicture {
            get {
                return ResourceManager.GetString("ribbon_RemoveCommentPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all comments.
        /// </summary>
        public static string ribbon_RemoveComments {
            get {
                return ResourceManager.GetString("ribbon_RemoveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all pictures.
        /// </summary>
        public static string ribbon_RemovePictures {
            get {
                return ResourceManager.GetString("ribbon_RemovePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string ribbon_RenameFile {
            get {
                return ResourceManager.GetString("ribbon_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string ribbon_RenameFileMenu {
            get {
                return ResourceManager.GetString("ribbon_RenameFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File Options.
        /// </summary>
        public static string ribbon_RenameFileOptions {
            get {
                return ResourceManager.GetString("ribbon_RenameFileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ribbon_Replace {
            get {
                return ResourceManager.GetString("ribbon_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay Gain.
        /// </summary>
        public static string ribbon_ReplayGain {
            get {
                return ResourceManager.GetString("ribbon_ReplayGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Layout.
        /// </summary>
        public static string ribbon_ResetLayout {
            get {
                return ResourceManager.GetString("ribbon_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Tags.
        /// </summary>
        public static string ribbon_RetrieveTags {
            get {
                return ResourceManager.GetString("ribbon_RetrieveTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rip.
        /// </summary>
        public static string ribbon_RipTab {
            get {
                return ResourceManager.GetString("ribbon_RipTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Folder Thumb.
        /// </summary>
        public static string ribbon_SaveFolderThumb {
            get {
                return ResourceManager.GetString("ribbon_SaveFolderThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Tag Edit.
        /// </summary>
        public static string ribbon_SingleTagEdit {
            get {
                return ResourceManager.GetString("ribbon_SingleTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag from Filename.
        /// </summary>
        public static string ribbon_TagFromFile {
            get {
                return ResourceManager.GetString("ribbon_TagFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag from Internet.
        /// </summary>
        public static string ribbon_TagFromInternet {
            get {
                return ResourceManager.GetString("ribbon_TagFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ribbon_TagTab {
            get {
                return ResourceManager.GetString("ribbon_TagTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate MP3.
        /// </summary>
        public static string ribbon_ValidateSong {
            get {
                return ResourceManager.GetString("ribbon_ValidateSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string songHeader_Album {
            get {
                return ResourceManager.GetString("songHeader_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string songHeader_AlbumArtist {
            get {
                return ResourceManager.GetString("songHeader_AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Sortname.
        /// </summary>
        public static string songHeader_AlbumSortName {
            get {
                return ResourceManager.GetString("songHeader_AlbumSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string songHeader_Artist {
            get {
                return ResourceManager.GetString("songHeader_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Sortname.
        /// </summary>
        public static string songHeader_ArtistSortName {
            get {
                return ResourceManager.GetString("songHeader_ArtistSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string songHeader_BitRate {
            get {
                return ResourceManager.GetString("songHeader_BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string songHeader_BPM {
            get {
                return ResourceManager.GetString("songHeader_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string songHeader_Channels {
            get {
                return ResourceManager.GetString("songHeader_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string songHeader_Comment {
            get {
                return ResourceManager.GetString("songHeader_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Information.
        /// </summary>
        public static string songHeader_CommercialInformation {
            get {
                return ResourceManager.GetString("songHeader_CommercialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string songHeader_Composer {
            get {
                return ResourceManager.GetString("songHeader_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string songHeader_Conductor {
            get {
                return ResourceManager.GetString("songHeader_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string songHeader_Copyright {
            get {
                return ResourceManager.GetString("songHeader_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Information.
        /// </summary>
        public static string songHeader_CopyrightInformation {
            get {
                return ResourceManager.GetString("songHeader_CopyrightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string songHeader_CreationTime {
            get {
                return ResourceManager.GetString("songHeader_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc #.
        /// </summary>
        public static string songHeader_Disc {
            get {
                return ResourceManager.GetString("songHeader_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Discs.
        /// </summary>
        public static string songHeader_DiscCount {
            get {
                return ResourceManager.GetString("songHeader_DiscCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string songHeader_Duration {
            get {
                return ResourceManager.GetString("songHeader_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded by.
        /// </summary>
        public static string songHeader_EncodedBy {
            get {
                return ResourceManager.GetString("songHeader_EncodedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate.
        /// </summary>
        public static string songHeader_Enumerate {
            get {
                return ResourceManager.GetString("songHeader_Enumerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string songHeader_FileName {
            get {
                return ResourceManager.GetString("songHeader_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string songHeader_FilePath {
            get {
                return ResourceManager.GetString("songHeader_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (kb).
        /// </summary>
        public static string songHeader_FileSize {
            get {
                return ResourceManager.GetString("songHeader_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string songHeader_Genre {
            get {
                return ResourceManager.GetString("songHeader_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string songHeader_Grouping {
            get {
                return ResourceManager.GetString("songHeader_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreted by.
        /// </summary>
        public static string songHeader_Interpreter {
            get {
                return ResourceManager.GetString("songHeader_Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string songHeader_LastWriteTime {
            get {
                return ResourceManager.GetString("songHeader_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string songHeader_Lyrics {
            get {
                return ResourceManager.GetString("songHeader_Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        public static string songHeader_MediaType {
            get {
                return ResourceManager.GetString("songHeader_MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Name.
        /// </summary>
        public static string songHeader_NewFileName {
            get {
                return ResourceManager.GetString("songHeader_NewFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. Discs.
        /// </summary>
        public static string songHeader_NumDisc {
            get {
                return ResourceManager.GetString("songHeader_NumDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Pics.
        /// </summary>
        public static string songHeader_NumPics {
            get {
                return ResourceManager.GetString("songHeader_NumPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. Tracks.
        /// </summary>
        public static string songHeader_NumTracks {
            get {
                return ResourceManager.GetString("songHeader_NumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Artist Information.
        /// </summary>
        public static string songHeader_OfficialArtistInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialArtistInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Audiofile Information.
        /// </summary>
        public static string songHeader_OfficialAudioFileInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialAudioFileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Audiosource Information.
        /// </summary>
        public static string songHeader_OfficialAudioSourceInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialAudioSourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Internet Radio Information.
        /// </summary>
        public static string songHeader_OfficialInternetRadioInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialInternetRadioInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Payment Information.
        /// </summary>
        public static string songHeader_OfficialPaymentInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialPaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off. Publisher Information.
        /// </summary>
        public static string songHeader_OfficialPublisherInformation {
            get {
                return ResourceManager.GetString("songHeader_OfficialPublisherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Album.
        /// </summary>
        public static string songHeader_OriginalAlbum {
            get {
                return ResourceManager.GetString("songHeader_OriginalAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Artist.
        /// </summary>
        public static string songHeader_OriginalArtist {
            get {
                return ResourceManager.GetString("songHeader_OriginalArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Filename.
        /// </summary>
        public static string songHeader_OriginalFileName {
            get {
                return ResourceManager.GetString("songHeader_OriginalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Lyricswriter.
        /// </summary>
        public static string songHeader_OriginalLyricsWriter {
            get {
                return ResourceManager.GetString("songHeader_OriginalLyricsWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Owner.
        /// </summary>
        public static string songHeader_OriginalOwner {
            get {
                return ResourceManager.GetString("songHeader_OriginalOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Release.
        /// </summary>
        public static string songHeader_OriginalRelease {
            get {
                return ResourceManager.GetString("songHeader_OriginalRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string songHeader_Picture {
            get {
                return ResourceManager.GetString("songHeader_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string songHeader_Publisher {
            get {
                return ResourceManager.GetString("songHeader_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string songHeader_Rating {
            get {
                return ResourceManager.GetString("songHeader_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Gain.
        /// </summary>
        public static string songHeader_ReplayGainAlbum {
            get {
                return ResourceManager.GetString("songHeader_ReplayGainAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Peak.
        /// </summary>
        public static string songHeader_ReplayGainAlbumPeak {
            get {
                return ResourceManager.GetString("songHeader_ReplayGainAlbumPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Gain.
        /// </summary>
        public static string songHeader_ReplayGainTrack {
            get {
                return ResourceManager.GetString("songHeader_ReplayGainTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Peak.
        /// </summary>
        public static string songHeader_ReplayGainTrackPeak {
            get {
                return ResourceManager.GetString("songHeader_ReplayGainTrackPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samplerate.
        /// </summary>
        public static string songHeader_SampleRate {
            get {
                return ResourceManager.GetString("songHeader_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string songHeader_Status {
            get {
                return ResourceManager.GetString("songHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string songHeader_SubTitle {
            get {
                return ResourceManager.GetString("songHeader_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string songHeader_TagType {
            get {
                return ResourceManager.GetString("songHeader_TagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textwriter.
        /// </summary>
        public static string songHeader_TextWriter {
            get {
                return ResourceManager.GetString("songHeader_TextWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string songHeader_Title {
            get {
                return ResourceManager.GetString("songHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Sortname.
        /// </summary>
        public static string songHeader_TitleSortName {
            get {
                return ResourceManager.GetString("songHeader_TitleSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string songHeader_Track {
            get {
                return ResourceManager.GetString("songHeader_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Tracks.
        /// </summary>
        public static string songHeader_TrackCount {
            get {
                return ResourceManager.GetString("songHeader_TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string songHeader_Unused {
            get {
                return ResourceManager.GetString("songHeader_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec.
        /// </summary>
        public static string songHeader_Version {
            get {
                return ResourceManager.GetString("songHeader_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string songHeader_Year {
            get {
                return ResourceManager.GetString("songHeader_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagfilter: Active.
        /// </summary>
        public static string statusBar_FilterActive {
            get {
                return ResourceManager.GetString("statusBar_FilterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagfilter: Inactive.
        /// </summary>
        public static string statusBar_FilterInactive {
            get {
                return ResourceManager.GetString("statusBar_FilterInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}.
        /// </summary>
        public static string statusBar_NumberOfFiles {
            get {
                return ResourceManager.GetString("statusBar_NumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Selected: {0}).
        /// </summary>
        public static string statusBar_NumberOfSelectedFiles {
            get {
                return ResourceManager.GetString("statusBar_NumberOfSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Format To List.
        /// </summary>
        public static string tagAndRename_AddFormat {
            get {
                return ResourceManager.GetString("tagAndRename_AddFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string tagAndRename_Album {
            get {
                return ResourceManager.GetString("tagAndRename_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string tagAndRename_AlbumArtist {
            get {
                return ResourceManager.GetString("tagAndRename_AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string tagAndRename_Artist {
            get {
                return ResourceManager.GetString("tagAndRename_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string tagAndRename_BitRate {
            get {
                return ResourceManager.GetString("tagAndRename_BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string tagAndRename_BPM {
            get {
                return ResourceManager.GetString("tagAndRename_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string tagAndRename_Comment {
            get {
                return ResourceManager.GetString("tagAndRename_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string tagAndRename_Composer {
            get {
                return ResourceManager.GetString("tagAndRename_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string tagAndRename_Conductor {
            get {
                return ResourceManager.GetString("tagAndRename_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Number.
        /// </summary>
        public static string tagAndRename_Disc {
            get {
                return ResourceManager.GetString("tagAndRename_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total # of discs.
        /// </summary>
        public static string tagAndRename_DiscTotal {
            get {
                return ResourceManager.GetString("tagAndRename_DiscTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates Files.
        /// </summary>
        public static string tagAndRename_Enumerate {
            get {
                return ResourceManager.GetString("tagAndRename_Enumerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Common Tags used?.
        /// </summary>
        public static string tagAndRename_FileExists {
            get {
                return ResourceManager.GetString("tagAndRename_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Filename.
        /// </summary>
        public static string tagAndRename_Filename {
            get {
                return ResourceManager.GetString("tagAndRename_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First &quot;n&quot; char of Album Artist.
        /// </summary>
        public static string tagAndRename_FirstNofAlbumArtist {
            get {
                return ResourceManager.GetString("tagAndRename_FirstNofAlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First &quot;n&quot; char of Artist.
        /// </summary>
        public static string tagAndRename_FirstNofArtist {
            get {
                return ResourceManager.GetString("tagAndRename_FirstNofArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ = Folder: to specify that parameters in front of it to be taken from the folder name.
        /// </summary>
        public static string tagAndRename_Folder {
            get {
                return ResourceManager.GetString("tagAndRename_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string tagAndRename_Genre {
            get {
                return ResourceManager.GetString("tagAndRename_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Group.
        /// </summary>
        public static string tagAndRename_Group {
            get {
                return ResourceManager.GetString("tagAndRename_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string tagAndRename_GroupBoxFormat {
            get {
                return ResourceManager.GetString("tagAndRename_GroupBoxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters (Click to add to the list).
        /// </summary>
        public static string tagAndRename_GroupBoxParam {
            get {
                return ResourceManager.GetString("tagAndRename_GroupBoxParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag from File Name.
        /// </summary>
        public static string tagAndRename_Header {
            get {
                return ResourceManager.GetString("tagAndRename_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string tagAndRename_Header_Rename {
            get {
                return ResourceManager.GetString("tagAndRename_Header_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter Format. Please Correct..
        /// </summary>
        public static string tagAndRename_InvalidParm {
            get {
                return ResourceManager.GetString("tagAndRename_InvalidParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified / remixed by.
        /// </summary>
        public static string tagAndRename_ModifiedBy {
            get {
                return ResourceManager.GetString("tagAndRename_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename too long. Please change it..
        /// </summary>
        public static string tagAndRename_NameTooLong {
            get {
                return ResourceManager.GetString("tagAndRename_NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Digits.
        /// </summary>
        public static string tagAndRename_NumberDigits {
            get {
                return ResourceManager.GetString("tagAndRename_NumberDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original:.
        /// </summary>
        public static string tagAndRename_Original {
            get {
                return ResourceManager.GetString("tagAndRename_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Changes.
        /// </summary>
        public static string tagAndRename_PreviewChanges {
            get {
                return ResourceManager.GetString("tagAndRename_PreviewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Format From List.
        /// </summary>
        public static string tagAndRename_RemoveFormat {
            get {
                return ResourceManager.GetString("tagAndRename_RemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Rename File {0}: {1}.
        /// </summary>
        public static string tagAndRename_Rename {
            get {
                return ResourceManager.GetString("tagAndRename_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string tagAndRename_StartAt {
            get {
                return ResourceManager.GetString("tagAndRename_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTitle.
        /// </summary>
        public static string tagAndRename_SubTitle {
            get {
                return ResourceManager.GetString("tagAndRename_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string tagAndRename_TabHeader_Parameter {
            get {
                return ResourceManager.GetString("tagAndRename_TabHeader_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string tagAndRename_TabHeader_Preview {
            get {
                return ResourceManager.GetString("tagAndRename_TabHeader_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string tagAndRename_Title {
            get {
                return ResourceManager.GetString("tagAndRename_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Number.
        /// </summary>
        public static string tagAndRename_Track {
            get {
                return ResourceManager.GetString("tagAndRename_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total # of tracks.
        /// </summary>
        public static string tagAndRename_TrackTotal {
            get {
                return ResourceManager.GetString("tagAndRename_TrackTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string tagAndRename_Unused {
            get {
                return ResourceManager.GetString("tagAndRename_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string tagAndRename_Year {
            get {
                return ResourceManager.GetString("tagAndRename_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album:.
        /// </summary>
        public static string tagEdit_Album {
            get {
                return ResourceManager.GetString("tagEdit_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist:.
        /// </summary>
        public static string tagEdit_AlbumArtist {
            get {
                return ResourceManager.GetString("tagEdit_AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist Sort:.
        /// </summary>
        public static string tagEdit_AlbumArtistSort {
            get {
                return ResourceManager.GetString("tagEdit_AlbumArtistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Sort:.
        /// </summary>
        public static string tagEdit_AlbumSort {
            get {
                return ResourceManager.GetString("tagEdit_AlbumSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist:.
        /// </summary>
        public static string tagEdit_Artist {
            get {
                return ResourceManager.GetString("tagEdit_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Sort:.
        /// </summary>
        public static string tagEdit_ArtistSort {
            get {
                return ResourceManager.GetString("tagEdit_ArtistSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string tagEdit_Comment {
            get {
                return ResourceManager.GetString("tagEdit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer:.
        /// </summary>
        public static string tagEdit_Composer {
            get {
                return ResourceManager.GetString("tagEdit_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor:.
        /// </summary>
        public static string tagEdit_Conductor {
            get {
                return ResourceManager.GetString("tagEdit_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Group:.
        /// </summary>
        public static string tagEdit_Content_Group {
            get {
                return ResourceManager.GetString("tagEdit_Content_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string tagEdit_Copyright {
            get {
                return ResourceManager.GetString("tagEdit_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc:.
        /// </summary>
        public static string tagEdit_Disc {
            get {
                return ResourceManager.GetString("tagEdit_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded By:.
        /// </summary>
        public static string tagEdit_EncodedBy {
            get {
                return ResourceManager.GetString("tagEdit_EncodedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Cover:.
        /// </summary>
        public static string tagEdit_FrontCover {
            get {
                return ResourceManager.GetString("tagEdit_FrontCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string tagEdit_Genre {
            get {
                return ResourceManager.GetString("tagEdit_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Genre(s).
        /// </summary>
        public static string tagEdit_Genre_Watermark {
            get {
                return ResourceManager.GetString("tagEdit_Genre_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get From File.
        /// </summary>
        public static string tagEdit_GetTrackLength {
            get {
                return ResourceManager.GetString("tagEdit_GetTrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Song Length from File.
        /// </summary>
        public static string tagEdit_GetTrackLength_Checkbox {
            get {
                return ResourceManager.GetString("tagEdit_GetTrackLength_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreted by:.
        /// </summary>
        public static string tagEdit_InterpretedBy {
            get {
                return ResourceManager.GetString("tagEdit_InterpretedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type:.
        /// </summary>
        public static string tagEdit_MediaType {
            get {
                return ResourceManager.GetString("tagEdit_MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Types:.
        /// </summary>
        public static string tagEdit_MediaTypes {
            get {
                return ResourceManager.GetString("tagEdit_MediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of Compilation.
        /// </summary>
        public static string tagEdit_PartOfCompilation {
            get {
                return ResourceManager.GetString("tagEdit_PartOfCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string tagEdit_Publisher {
            get {
                return ResourceManager.GetString("tagEdit_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove existing pictures.
        /// </summary>
        public static string tagEdit_Remove_Existing_Pictures {
            get {
                return ResourceManager.GetString("tagEdit_Remove_Existing_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Length (ms):.
        /// </summary>
        public static string tagEdit_Songlength {
            get {
                return ResourceManager.GetString("tagEdit_Songlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle:.
        /// </summary>
        public static string tagEdit_SubTitle {
            get {
                return ResourceManager.GetString("tagEdit_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Tags.
        /// </summary>
        public static string tagEdit_TabHeader_Additional {
            get {
                return ResourceManager.GetString("tagEdit_TabHeader_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Information.
        /// </summary>
        public static string tagEdit_TabHeader_Detailed_Information {
            get {
                return ResourceManager.GetString("tagEdit_TabHeader_Detailed_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Details.
        /// </summary>
        public static string tagEdit_TabHeader_Lyrics {
            get {
                return ResourceManager.GetString("tagEdit_TabHeader_Lyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Tags.
        /// </summary>
        public static string tagEdit_TabHeader_Main {
            get {
                return ResourceManager.GetString("tagEdit_TabHeader_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Details.
        /// </summary>
        public static string tagEdit_TabHeader_Pictures {
            get {
                return ResourceManager.GetString("tagEdit_TabHeader_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics / Text Writer:.
        /// </summary>
        public static string tagEdit_TextWriter {
            get {
                return ResourceManager.GetString("tagEdit_TextWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string tagEdit_Title {
            get {
                return ResourceManager.GetString("tagEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Sort:.
        /// </summary>
        public static string tagEdit_TitleSort {
            get {
                return ResourceManager.GetString("tagEdit_TitleSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Lyrics from File.
        /// </summary>
        public static string tagEdit_ToolTip_Lyrics_GetFile {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Lyrics_GetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Lyrics from configured Sites.
        /// </summary>
        public static string tagEdit_ToolTip_Lyrics_GetInternet {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Lyrics_GetInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lyrics.
        /// </summary>
        public static string tagEdit_ToolTip_Lyrics_Remove {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Lyrics_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cover Art from File.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_GetCoverArt_File {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_GetCoverArt_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cover Art from configured Sites.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_GetCoverArt_Internet {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_GetCoverArt_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Cover Art.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_Remove_CoverArt {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_Remove_CoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Cover Art.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_RemoveDetail_CoverArt {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_RemoveDetail_CoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Cover Art to folder.jpg.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_Save_CoverArt {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_Save_CoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Cover Art to file.
        /// </summary>
        public static string tagEdit_ToolTip_Picture_SaveDetail_CoverArt {
            get {
                return ResourceManager.GetString("tagEdit_ToolTip_Picture_SaveDetail_CoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track:.
        /// </summary>
        public static string tagEdit_Track {
            get {
                return ResourceManager.GetString("tagEdit_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string tagEdit_Year {
            get {
                return ResourceManager.GetString("tagEdit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treeview.
        /// </summary>
        public static string treeview_Header {
            get {
                return ResourceManager.GetString("treeview_Header", resourceCulture);
            }
        }
    }
}
